spring:
  application:
    name: mybatis-extension
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test
    username: root
    password: 12345
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
  h2:
    console:
      enabled: true
      #进行该配置，你就可以通过YOUR_URL/h2访问h2 web consloe。YOUR_URL是你程序的访问URl。默认为/h2-console
      path: /h2
      # 进行该配置后，h2 web consloe就可以在远程访问了。否则只能在本机访问。
      settings:
        web-allow-others: true
mybatis-plus:
  mapper-locations: [ "classpath*:/mapper/**/*.xml" ]
  type-aliases-package: com.leijs.mybatis.extension.app.dal.dataobject
  configuration:
    jdbc-type-for-null: 'null'
  global-config:
    db-config:
      id-type: auto # 主键自增
      logic-delete-value: 1
      logic-not-delete-value: 0
      logic-delete-field: flag
